CC = g++
MKDIR = mkdir

SRCDIR = src
BUILDDIR = build
OS = $(shell uname -s)
CFLAGS = 
INCLUDES = 
LFLAGS = 
LIBS = 
MAIN = 

all:
	${MAKE} -f Makefile.$(OS)

clean:
	${MAKE} -f Makefile.$(OS) clean

# DO NOT DELETE THIS LINE -- make depend needs it

