/* Copyright 2010 Santiago Ontanon and Ashwin Ram */

/* The following code was generated by JFlex 1.4.3 on 15/02/10 14:54 */

/*
  ----------------------------------------------
                    USER CODE
  ----------------------------------------------
 */
package gatech.mmpm.tools.expressionparser;

import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 15/02/10 14:54 from the specification file
 * <tt>src/gatech/mmpm/tools/expressionparser/Lexer.lex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     7,  7,  7,  7,  7,  7,  7,  7,  7,  3,  2,  0,  3,  1,  7,  7, 
     7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  0,  0,  0,  0, 
     3, 34, 23,  0,  6, 31, 32,  0, 25, 26,  5, 30, 24, 13, 22,  4, 
    10,  8,  8,  8,  8,  8,  8,  8,  8,  8, 28,  0, 35, 29, 36, 27, 
     0,  9,  9,  9,  9, 12,  9,  6,  6,  6,  6,  6,  6,  6,  6,  6, 
     6,  6,  6,  6,  6,  6,  6,  6, 11,  6,  6,  0, 37,  0,  0,  6, 
     0, 19,  9,  9,  9, 17, 18,  6,  6,  6,  6,  6, 20,  6, 38,  6, 
     6,  6, 15, 21, 14, 16,  6,  6, 11,  6,  6,  0, 33,  0,  0,  7, 
     7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7, 
     7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7, 
     0,  0,  6,  6,  6,  6,  0,  0,  0,  0,  6,  0,  0,  7,  0,  0, 
     0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0, 
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6, 
     6,  6,  6,  6,  6,  6,  6,  0,  6,  6,  6,  6,  6,  6,  6,  6, 
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6, 
     6,  6,  6,  6,  6,  6,  6,  0,  6,  6,  6,  6,  6,  6,  6,  6
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\2\5\1\1\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\2\1\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\2\0\1\27\1\30\1\0\2\5\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\3\0\1\43\2\5\1\0\1\27\1\0\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[58];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\116\0\234\0\116\0\303"+
    "\0\352\0\u0111\0\116\0\u0138\0\u015f\0\u0186\0\116\0\116"+
    "\0\116\0\116\0\116\0\116\0\u01ad\0\116\0\116\0\u01d4"+
    "\0\u01fb\0\u0222\0\u0249\0\u0270\0\u0297\0\116\0\u02be\0\u02e5"+
    "\0\u030c\0\u0333\0\u035a\0\u0381\0\u03a8\0\u03cf\0\116\0\116"+
    "\0\116\0\116\0\116\0\116\0\116\0\116\0\116\0\116"+
    "\0\u03f6\0\u041d\0\u0444\0\u0381\0\u046b\0\u0492\0\u04b9\0\u04e0"+
    "\0\u04e0\0\303";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[58];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\10\1\12\2\10\1\13\1\14\3\10\1\15\3\10"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\3"+
    "\1\10\1\35\2\0\24\35\1\36\15\35\1\37\1\35"+
    "\51\0\1\5\50\0\1\40\1\41\47\0\7\10\1\0"+
    "\10\10\20\0\1\10\10\0\1\11\1\0\1\11\13\0"+
    "\1\42\30\0\1\43\1\0\1\43\1\44\12\0\1\42"+
    "\26\0\7\10\1\0\1\10\1\45\6\10\20\0\1\10"+
    "\6\0\7\10\1\0\5\10\1\46\2\10\20\0\1\10"+
    "\10\0\1\42\1\0\1\42\71\0\1\47\51\0\1\50"+
    "\47\0\1\51\42\0\1\52\46\0\1\53\46\0\1\54"+
    "\11\0\1\35\2\0\24\35\1\0\15\35\1\0\1\35"+
    "\16\0\1\55\1\56\7\0\1\57\16\0\1\60\1\40"+
    "\1\4\1\5\44\40\5\61\1\62\41\61\10\0\1\42"+
    "\1\0\1\42\1\0\1\63\4\0\1\63\35\0\1\43"+
    "\1\0\1\43\13\0\1\42\30\0\3\64\1\0\1\64"+
    "\4\0\3\64\31\0\7\10\1\0\2\10\1\65\5\10"+
    "\20\0\1\10\6\0\7\10\1\0\6\10\1\66\1\10"+
    "\20\0\1\10\5\61\1\67\41\61\4\0\1\5\1\62"+
    "\51\0\1\70\1\0\1\70\2\0\1\71\20\0\1\71"+
    "\16\0\7\10\1\0\3\10\1\72\4\10\20\0\1\10"+
    "\6\0\7\10\1\0\7\10\1\65\20\0\1\10\4\61"+
    "\1\5\1\67\41\61\10\0\1\70\1\0\1\70\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1287];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\1\1\1\11\3\1\1\11"+
    "\3\1\6\11\1\1\2\11\6\1\1\11\1\1\2\0"+
    "\2\1\1\0\2\1\12\11\3\0\3\1\1\0\1\1"+
    "\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[58];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

	/**
	 * String buffer where strings are built keeping into account
	 * escape characters.
	 */
	StringBuffer string = new StringBuffer();

	/**
	 * A new java_cup.runtime.Symbol is created, with no attached information.
	 */
	private Symbol symbol(int type){
		return new Symbol(type,yyline,yycolumn);
	}

	/**
	 * A new java_cup.runtime.Symbol is created, with an object
	 * as attached information.
	 */
	private Symbol symbol(int type,Object value){
		return new Symbol(type,yyline,yycolumn,value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { return symbol(sym.NOT_OP, OperatorToken.NOT);
          }
        case 37: break;
        case 7: 
          { return symbol(sym.ADD_OP, OperatorToken.MINUS);
          }
        case 38: break;
        case 24: 
          { return symbol(sym.INTEGER_LITERAL, new Integer(Integer.parseInt(yytext(), 8)));
          }
        case 39: break;
        case 26: 
          { return symbol(sym.AND_OP, OperatorToken.AND);
          }
        case 40: break;
        case 10: 
          { return symbol(sym.LPAR);
          }
        case 41: break;
        case 31: 
          { string.append('\t');
          }
        case 42: break;
        case 8: 
          { string.setLength(0); yybegin(STRING);
          }
        case 43: break;
        case 11: 
          { return symbol(sym.RPAR);
          }
        case 44: break;
        case 21: 
          { yybegin(YYINITIAL);
       return symbol(sym.STRING_LITERAL, string.toString());
          }
        case 45: break;
        case 22: 
          { string.append('\\');
          }
        case 46: break;
        case 30: 
          { return symbol(sym.RELATIONAL_OP, OperatorToken.GE);
          }
        case 47: break;
        case 32: 
          { string.append('\r');
          }
        case 48: break;
        case 29: 
          { return symbol(sym.RELATIONAL_OP, OperatorToken.LE);
          }
        case 49: break;
        case 2: 
          { /* Ignore */
          }
        case 50: break;
        case 23: 
          { return symbol(sym.FLOAT_LITERAL, new Float(Float.parseFloat(yytext())));
          }
        case 51: break;
        case 27: 
          { return symbol(sym.OR_OP, OperatorToken.OR);
          }
        case 52: break;
        case 6: 
          { return symbol(sym.INTEGER_LITERAL, new Integer(Integer.parseInt(yytext())));
          }
        case 53: break;
        case 25: 
          { return symbol(sym.EQ_OP, OperatorToken.EQ);
          }
        case 54: break;
        case 5: 
          { return symbol(sym.IDENTIFIER, yytext());
          }
        case 55: break;
        case 33: 
          { string.append('\"');
          }
        case 56: break;
        case 13: 
          { return symbol(sym.COLON);
          }
        case 57: break;
        case 28: 
          { return symbol(sym.EQ_OP, OperatorToken.NE);
          }
        case 58: break;
        case 12: 
          { return symbol(sym.QUESTION);
          }
        case 59: break;
        case 14: 
          { return symbol(sym.EQUAL);
          }
        case 60: break;
        case 19: 
          { return symbol(sym.RELATIONAL_OP, OperatorToken.GT);
          }
        case 61: break;
        case 1: 
          { System.err.println("TODO: ilegal token <" + yytext() + " line " + (yyline + 1) + " column " + (yycolumn + 1));
          }
        case 62: break;
        case 18: 
          { return symbol(sym.RELATIONAL_OP, OperatorToken.LT);
          }
        case 63: break;
        case 34: 
          { string.append('\n');
          }
        case 64: break;
        case 3: 
          { return symbol(sym.MULT_OP, OperatorToken.DIV);
          }
        case 65: break;
        case 15: 
          { return symbol(sym.ADD_OP, OperatorToken.ADD);
          }
        case 66: break;
        case 36: 
          { return symbol(sym.BOOLEAN_LITERAL, new Boolean(Boolean.parseBoolean(yytext())));
          }
        case 67: break;
        case 16: 
          { return symbol(sym.MULT_OP, OperatorToken.MOD);
          }
        case 68: break;
        case 9: 
          { return symbol(sym.COMMA);
          }
        case 69: break;
        case 35: 
          { return symbol(sym.INTEGER_LITERAL, new Integer(Integer.parseInt(yytext().substring(2), 16)));
          }
        case 70: break;
        case 20: 
          { string.append( yytext() );
          }
        case 71: break;
        case 4: 
          { return symbol(sym.MULT_OP, OperatorToken.MULT);
          }
        case 72: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
