/* Copyright 2010 Santiago Ontanon and Ashwin Ram */


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 15 14:54:37 CET 2010
//----------------------------------------------------

package gatech.mmpm.tools.expressionparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT_OP = 9;
  public static final int QUESTION = 5;
  public static final int ADD_OP = 8;
  public static final int EQUAL = 7;
  public static final int BOOLEAN_LITERAL = 18;
  public static final int IDENTIFIER = 15;
  public static final int AND_OP = 11;
  public static final int EQ_OP = 12;
  public static final int COLON = 6;
  public static final int NOT_OP = 14;
  public static final int RELATIONAL_OP = 13;
  public static final int STRING_LITERAL = 17;
  public static final int COMMA = 2;
  public static final int EOF = 0;
  public static final int OR_OP = 10;
  public static final int error = 1;
  public static final int INTEGER_LITERAL = 16;
  public static final int RPAR = 4;
  public static final int FLOAT_LITERAL = 19;
  public static final int LPAR = 3;
}

